### ISSUE TITLE
1.13 support

### ISSUE THREAD

**Issue by datatags** [HexagonMC/BungeeSuiteChat#4]
I’d like to continue using this in 1.13, but 1.13 seems to require a namespace and a channel for BungeeCord messaging.  Since BSChat doesn’t do that, it fails to load.

Yes, I should probably abandon it since it is abandoned but I haven’t fount a satisfactory replacement yet.

I would fix and compile myself except I know nothing about maven.  If anyone is still watching this, I would really appreciate a fix.

Thanks!

**Comment by johnfriedrich** [comment]
Hi,
we actually still use this plugin, but are not using channels for messaging. If I remember correct, 1.13 just require the channel to be lowercased?

BTW: You can compile this without maven or simply hit import Maven project in your IDE

**Comment by datatags** [comment]
This is the error I got:
`[16:10:18 ERROR]: Error occurred while enabling Chat v0.5b-${BUILD_NUMBER} (Is it up to date?)
java.lang.IllegalArgumentException: Channel must contain : separator (attempted to use BSChat)`

Also, about maven, I imported as a GitHub project and Eclipse recognizes it as such but I need the dependencies still.  That and I want to compile it against 1.13 but couldn’t find a way to change it from what it was at.  Thanks!

**Comment by johnfriedrich** [comment]
gesuit:bschat should do it. But guess the bungeepart has to be changed aswelll
Do the following:
Clone your project in your eclipse workspace via command line or zip extract.
Eclipse--> import: existing maven project. Select cloned folder --> import.
Right click on newly imported project --> Run as maven install.
Done. You can find builds in your clonedfolder/target
